from django.urls import path
from . import views

urlpatterns = [
    #path('', views.catalogo_productos, name='catalogo_productos'),
    #path('producto/<int:prod_id>/', views.detalle_catalogo, name='detalle_catalogo'),
    path('registro/', views.registro_cliente, name='registro_cliente'),
    path('registro/validar-documento/', views.validar_documento_cliente, name='validar_documento'),
    path('registro/validar-email/', views.validar_email_cliente, name='validar_email'),
    path('cambiar-contrasena/', views.cambiar_contrasena, name='cambiar_contrasena'),
    path('inicio/', views.inicio, name='inicio'),
    path('motos/', views.catalogo_motos, name='catalogo_motos'),
    path('motos/busqueda/', views.busqueda_motos, name='busqueda_motos'),
    path("moto/<int:prod_id>/", views.detalle_moto, name="detalle_moto"),
    path("moto/<int:prod_id>/cotizar/", views.cotizar_moto, name="cotizar_moto"),
    path("enviar-cotizacion/", views.enviar_cotizacion, name="enviar_cotizacion"),
    path('accesorios/', views.catalogo_accesorios, name='catalogo_accesorios'),
    path('accesorios/busqueda/', views.busqueda_accesorios, name='busqueda_accesorios'),
    path("accesorio/<int:prod_id>/", views.detalle_accesorio, name="detalle_accesorio"),
    path("accesorio/agregar-a-carrito/", views.agregar_a_carrito, name="agregar_a_carrito"),
    path("carrito/", views.vista_carrito, name="vista_carrito"),
    path('carrito/eliminar/', views.eliminar_producto_carrito, name='eliminar_producto_carrito'),
    path('carrito/cambiar-cantidad/', views.cambiar_cantidad_carrito, name='cambiar_cantidad_carrito'),
    path('carrito/factura/set/', views.factura_set, name='factura_set'),
    path('carrito/factura/clear/', views.factura_clear, name='factura_clear'),
    path('carrito/cliente/buscar/', views.cliente_buscar, name='cliente_buscar'),
    path('carrito/cliente/registrar/', views.cliente_registrar, name='cliente_registrar'),
    path("carrito/crear_preferencia/", views.crear_preferencia, name="crear_preferencia"),
    path("carrito/pago/exito/", views.pago_exito, name="pago_exito"),
    path("carrito/pago/error/", views.pago_error, name="pago_error"),
    path("carrito/pago/pendiente/", views.pago_pendiente, name="pago_pendiente"),
]